/*
 * This file was automatically generated by EvoSuite
 */

package corina.prefs;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.prefs.PrefsEvent;
import org.junit.BeforeClass;

public class PrefsEventEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      PrefsEvent prefsEvent0 = new PrefsEvent((Object) "", "");
      String string0 = prefsEvent0.getPref();
      assertEquals("", string0);
  }
}
