/*
 * This file was automatically generated by EvoSuite
 */

package corina.util;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.util.Center;
import java.awt.HeadlessException;
import java.awt.Window;
import org.junit.BeforeClass;

public class CenterEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        Center.center((Window) null, (Window) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try {
        Center.center((Window) null);
        fail("Expecting exception: HeadlessException");
      } catch(HeadlessException e) {
      }
  }
}
