/*
 * This file was automatically generated by EvoSuite
 */

package corina.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class DocumentListener2EvoSuiteTest {


}
