/*
 * This file was automatically generated by EvoSuite
 */

package corina.util;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.util.OKCancel;
import javax.swing.JButton;
import org.junit.BeforeClass;

public class OKCancelEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      JButton jButton0 = new JButton();
      // Undeclared exception!
      try {
        OKCancel.addKeyboardDefaults(jButton0);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
