/*
 * This file was automatically generated by EvoSuite
 */

package corina.gui.menus;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.gui.menus.EditMenu;
import org.junit.BeforeClass;

public class EditMenuEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      EditMenu editMenu0 = null;
      try {
        editMenu0 = new EditMenu();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
