/*
 * This file was automatically generated by EvoSuite
 */

package corina.gui.menus;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.gui.menus.WindowMenu;
import javax.swing.JFrame;
import org.junit.BeforeClass;

public class WindowMenuEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      WindowMenu windowMenu0 = null;
      try {
        windowMenu0 = new WindowMenu((JFrame) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
