/*
 * This file was automatically generated by EvoSuite
 */

package corina.browser;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.browser.Browser;
import corina.browser.BrowserContextMenu;
import org.junit.BeforeClass;

public class BrowserContextMenuEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      BrowserContextMenu browserContextMenu0 = null;
      try {
        browserContextMenu0 = new BrowserContextMenu((Browser) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
