/*
 * This file was automatically generated by EvoSuite
 */

package corina.browser;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.browser.BrowserComponent;
import java.util.List;
import org.junit.BeforeClass;

public class BrowserComponentEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      BrowserComponent browserComponent0 = new BrowserComponent((List) null);
  }
}
