/*
 * This file was automatically generated by EvoSuite
 */

package corina.graph;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.BeforeClass;

public class GraphFileMenuEvoSuiteTest {


}
