/*
 * This file was automatically generated by EvoSuite
 */

package corina.map;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.map.MapFile;
import corina.map.Palette;
import org.junit.BeforeClass;

public class PaletteEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        Palette.getColor((MapFile.Header) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  @Test
  public void test1()  throws Throwable  {
      Palette palette0 = new Palette();
      assertNotNull(palette0);
  }

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        Palette.getStroke((MapFile.Header) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
