/*
 * This file was automatically generated by EvoSuite
 */

package corina.map;

import org.junit.Test;
import static org.junit.Assert.*;
import corina.map.Raw2Pack;
import org.junit.BeforeClass;

public class Raw2PackEvoSuiteTest {



  @Test
  public void test0()  throws Throwable  {
      Raw2Pack raw2Pack0 = new Raw2Pack();
  }
}
