/*
 * This file was automatically generated by EvoSuite
 */

package httpanalyzer;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

public class HttpAnalyzerAboutBoxEvoSuiteTest {

}
